import {
  IntroductoryMaterial,
  Assessment,
  GuidanceSession,
  LearningPathStep,
  Recommendation,
  StudentProgress,
} from '../types/refresher';

export const INITIAL_PROGRESS: StudentProgress = {
  overallProgressPercent: 68,
  sessionsCompleted: 4,
  sessionsTotal: 6,
  assessmentsCompleted: 5,
  assessmentsPassed: 4,
  assessmentsTotal: 8,
  materialsCompleted: 7,
  materialsTotal: 10,
  currentStage: 'Step 3: Practice Exercises',
  streakDays: 5,
};

export const INITIAL_MATERIALS: IntroductoryMaterial[] = [
  {
    id: 'mat-1',
    title: 'Data Structures Prerequisites & Memory Layout',
    description: 'Master arrays, pointers, memory allocation, and time complexity notation before diving into tree & graph algorithms.',
    subject: 'Data Structures',
    duration: '25 mins',
    difficulty: 'Beginner',
    type: 'PDF',
    status: 'Completed',
    contentUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  },
  {
    title: 'Object-Oriented Programming (OOP) Core Principles',
    id: 'mat-2',
    description: 'Comprehensive breakdown of Encapsulation, Inheritance, Polymorphism, and Abstraction with Java & C++ examples.',
    subject: 'Core Java',
    duration: '40 mins',
    difficulty: 'Beginner',
    type: 'Video',
    status: 'Completed',
    videoUrl: 'https://www.youtube.com/embed/pTB0EiLXUC8',
  },
  {
    id: 'mat-3',
    title: 'Relational Database Fundamentals & SQL Queries',
    description: 'Learn ER diagrams, table normalization (1NF-3NF), primary/foreign keys, SELECT, JOINs, and indexing.',
    subject: 'Database Systems',
    duration: '30 mins',
    difficulty: 'Beginner',
    type: 'Notes',
    status: 'Completed',
    notesSnippet: '### Relational Database Fundamentals\n\n1. **Tables & Schemas**: Databases store structured data in rows and columns.\n2. **Primary Key**: Unique identifier for each record in a table.\n3. **Foreign Key**: Establishes relationships between tables.\n4. **JOIN Operations**: INNER JOIN, LEFT JOIN, RIGHT JOIN, and FULL OUTER JOIN.\n5. **Normalization**: Process of reducing redundancy and organizing attributes efficiently.',
  },
  {
    id: 'mat-4',
    title: 'JavaScript ES6+ Essentials & Asynchronous Programming',
    description: 'Understand closures, promises, async/await, event loop, arrow functions, and array methods (map, filter, reduce).',
    subject: 'Web Development',
    duration: '35 mins',
    difficulty: 'Beginner',
    type: 'Video',
    status: 'Completed',
    videoUrl: 'https://www.youtube.com/embed/NCwa_xi0Uuc',
  },
  {
    id: 'mat-5',
    title: 'Python for Data Analysis & Automation Quick Guide',
    description: 'Essentials of Python syntax, data types, lists, dictionaries, list comprehensions, and basic file handling.',
    subject: 'Python',
    duration: '20 mins',
    difficulty: 'Beginner',
    type: 'PDF',
    status: 'Completed',
    contentUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  },
  {
    id: 'mat-6',
    title: 'Operating System Basics: Processes, Threads & Concurrency',
    description: 'Explore process synchronization, context switching, deadlock conditions, and CPU scheduling algorithms.',
    subject: 'Operating Systems',
    duration: '45 mins',
    difficulty: 'Beginner',
    type: 'Notes',
    status: 'Completed',
    notesSnippet: '### OS Core Concepts\n\n- **Process**: Program in execution with code, data, heap, and stack.\n- **Thread**: Light-weight unit of execution sharing process memory space.\n- **Mutex vs Semaphore**: Mutex locks critical section for single thread; Semaphore maintains counter.\n- **Deadlock Conditions**: Mutual exclusion, Hold & wait, No preemption, Circular wait.',
  },
  {
    id: 'mat-7',
    title: 'Computer Networks Primer: OSI Model & TCP/IP Protocol',
    description: 'Detailed explanation of layers, IP addressing, subnetting, TCP vs UDP, DNS resolution, and HTTP/HTTPS headers.',
    subject: 'Computer Networks',
    duration: '30 mins',
    difficulty: 'Beginner',
    type: 'PDF',
    status: 'Completed',
    contentUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  },
  {
    id: 'mat-8',
    title: 'Git & GitHub Version Control Cheatsheet',
    description: 'Hands-on reference for branching, merging, rebase, handling merge conflicts, pull requests, and commit conventions.',
    subject: 'Tools & DevOps',
    duration: '15 mins',
    difficulty: 'Beginner',
    type: 'Notes',
    status: 'In Progress',
    notesSnippet: '### Essential Git Workflow\n\n1. `git checkout -b feature/new-branch`\n2. `git add .` && `git commit -m "feat: message"`\n3. `git push origin feature/new-branch`\n4. `git pull --rebase origin main` to sync updates cleanly.',
  },
  {
    id: 'mat-9',
    title: 'System Design Fundamentals: Monolith vs Microservices',
    description: 'Architectural overview of load balancing, horizontal vs vertical scaling, caching (Redis), and message queues.',
    subject: 'System Design',
    duration: '50 mins',
    difficulty: 'Beginner',
    type: 'Video',
    status: 'Not Started',
    videoUrl: 'https://www.youtube.com/embed/SqsRGlrNP1w',
  },
  {
    id: 'mat-10',
    title: 'RESTful API Design Best Practices & JSON Schema',
    description: 'Standard HTTP methods (GET, POST, PUT, DELETE), status codes, path parameters, query params, and authentication headers.',
    subject: 'Web Development',
    duration: '25 mins',
    difficulty: 'Beginner',
    type: 'PDF',
    status: 'Not Started',
    contentUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  },
];

export const INITIAL_ASSESSMENTS: Assessment[] = [
  {
    id: 'quiz-1',
    title: 'Data Structures Fundamentals Diagnostic Quiz',
    subject: 'Data Structures',
    questionsCount: 5,
    estimatedTime: '15 mins',
    difficulty: 'Beginner',
    passingPercentage: 70,
    attemptsRemaining: 2,
    maxAttempts: 3,
    lastScore: 80,
    status: 'Passed',
    questions: [
      {
        id: 'q1-1',
        question: 'What is the worst-case time complexity of accessing an element in an array by index?',
        options: ['O(1)', 'O(n)', 'O(log n)', 'O(n^2)'],
        correctAnswerIndex: 0,
        explanation: 'Arrays store elements in contiguous memory locations, allowing direct O(1) index calculation.',
      },
      {
        id: 'q1-2',
        question: 'Which data structure operates on a Last-In, First-Out (LIFO) principle?',
        options: ['Queue', 'Stack', 'Linked List', 'Binary Tree'],
        correctAnswerIndex: 1,
        explanation: 'A Stack follows the LIFO order where the last pushed element is popped first.',
      },
      {
        id: 'q1-3',
        question: 'What is the auxiliary space complexity of a standard singly linked list with N nodes?',
        options: ['O(1)', 'O(N)', 'O(N log N)', 'O(N^2)'],
        correctAnswerIndex: 1,
        explanation: 'A linked list allocates memory dynamically for each of the N nodes.',
      },
      {
        id: 'q1-4',
        question: 'Which sorting algorithm has a guaranteed O(N log N) worst-case time complexity?',
        options: ['Quick Sort', 'Merge Sort', 'Bubble Sort', 'Insertion Sort'],
        correctAnswerIndex: 1,
        explanation: 'Merge Sort consistently divides arrays into halves and merges in O(N log N) time.',
      },
      {
        id: 'q1-5',
        question: 'In a Hash Table, what happens during a hash collision?',
        options: [
          'The data is permanently erased',
          'Multiple keys map to the same hash index',
          'The array size automatically quadruples',
          'An infinite loop occurs',
        ],
        correctAnswerIndex: 1,
        explanation: 'Collisions occur when two distinct keys yield the same hash value, resolved by chaining or open addressing.',
      },
    ],
  },
  {
    id: 'quiz-2',
    title: 'Object-Oriented Programming (OOP) Assessment',
    subject: 'Core Java',
    questionsCount: 5,
    estimatedTime: '20 mins',
    difficulty: 'Beginner',
    passingPercentage: 75,
    attemptsRemaining: 1,
    maxAttempts: 3,
    lastScore: 80,
    status: 'Passed',
    questions: [
      {
        id: 'q2-1',
        question: 'Which OOP feature allows a function or operator to exhibit different behaviors based on input parameters?',
        options: ['Encapsulation', 'Polymorphism', 'Inheritance', 'Abstraction'],
        correctAnswerIndex: 1,
        explanation: 'Polymorphism (method overloading/overriding) enables dynamic or compile-time behavior changes.',
      },
      {
        id: 'q2-2',
        question: 'What keyword in Java prevents a class from being inherited?',
        options: ['static', 'final', 'abstract', 'private'],
        correctAnswerIndex: 1,
        explanation: 'Declaring a class as `final` prohibits any subclassing.',
      },
      {
        id: 'q2-3',
        question: 'Encapsulation is primarily achieved through which mechanism?',
        options: ['Global variables', 'Private fields with getters and setters', 'Multiple inheritance', 'Recursive calls'],
        correctAnswerIndex: 1,
        explanation: 'Encapsulation restricts direct access to fields by using private modifiers and public methods.',
      },
      {
        id: 'q2-4',
        question: 'Can an Abstract Class be instantiated directly using `new`?',
        options: ['Yes', 'No', 'Only in static context', 'Only in Java 17+'],
        correctAnswerIndex: 1,
        explanation: 'Abstract classes cannot be directly instantiated; they must be extended by concrete subclasses.',
      },
      {
        id: 'q2-5',
        question: 'What is method overriding in child classes?',
        options: [
          'Creating a method with the same name but different arguments',
          'Redefining a parent class method with the exact same signature',
          'Deleting a method from parent class',
          'Calling private constructors',
        ],
        correctAnswerIndex: 1,
        explanation: 'Overriding allows a child class to provide a specific implementation of a parent method with identical signature.',
      },
    ],
  },
  {
    id: 'quiz-3',
    title: 'Database & SQL Core Concepts Assessment',
    subject: 'Database Systems',
    questionsCount: 5,
    estimatedTime: '15 mins',
    difficulty: 'Beginner',
    passingPercentage: 70,
    attemptsRemaining: 2,
    maxAttempts: 3,
    lastScore: 90,
    status: 'Passed',
    questions: [
      {
        id: 'q3-1',
        question: 'Which SQL clause is used to filter records AFTER an aggregation function (GROUP BY)?',
        options: ['WHERE', 'HAVING', 'ORDER BY', 'LIMIT'],
        correctAnswerIndex: 1,
        explanation: '`HAVING` filters aggregated records, whereas `WHERE` filters rows before aggregation.',
      },
      {
        id: 'q3-2',
        question: 'What does 1NF (First Normal Form) require?',
        options: ['Atomic values in columns', 'No transitive dependencies', 'Foreign keys on all tables', 'B-Tree indexes'],
        correctAnswerIndex: 0,
        explanation: '1NF demands that each column contains atomic (indivisible) values and no repeating groups.',
      },
      {
        id: 'q3-3',
        question: 'Which JOIN returns all rows from the left table even if there are no matches in the right table?',
        options: ['INNER JOIN', 'LEFT JOIN', 'RIGHT JOIN', 'CROSS JOIN'],
        correctAnswerIndex: 1,
        explanation: 'LEFT JOIN keeps all records from the left side and fills missing right columns with NULL.',
      },
      {
        id: 'q3-4',
        question: 'In ACID properties of database transactions, what does "A" stand for?',
        options: ['Availability', 'Atomicity', 'Authentication', 'Asynchrony'],
        correctAnswerIndex: 1,
        explanation: 'Atomicity ensures that all operations in a transaction succeed completely or fail completely (all-or-nothing).',
      },
      {
        id: 'q3-5',
        question: 'What primary advantage does an Database Index provide?',
        options: ['Faster INSERT operations', 'Faster SELECT lookup queries', 'Reduced disk space', 'Automatic encryption'],
        correctAnswerIndex: 1,
        explanation: 'Indexes create lookup tables (e.g. B-Trees) that drastically speed up data retrieval queries.',
      },
    ],
  },
  {
    id: 'quiz-4',
    title: 'JavaScript & ES6 Fundamentals Quiz',
    subject: 'Web Development',
    questionsCount: 5,
    estimatedTime: '15 mins',
    difficulty: 'Beginner',
    passingPercentage: 75,
    attemptsRemaining: 3,
    maxAttempts: 3,
    lastScore: 85,
    status: 'Passed',
    questions: [
      {
        id: 'q4-1',
        question: 'What is the output of `typeof NaN` in JavaScript?',
        options: ['"number"', '"nan"', '"undefined"', '"object"'],
        correctAnswerIndex: 0,
        explanation: 'In JS specification, NaN (Not a Number) is categorized under the numeric primitive type.',
      },
      {
        id: 'q4-2',
        question: 'Which variable declaration scope is block-scoped?',
        options: ['var', 'let and const', 'function', 'global'],
        correctAnswerIndex: 1,
        explanation: '`let` and `const` are scoped to the nearest enclosing block `{}`.',
      },
      {
        id: 'q4-3',
        question: 'What method converts a JSON string into a JavaScript object?',
        options: ['JSON.stringify()', 'JSON.parse()', 'JSON.toObject()', 'Object.fromJSON()'],
        correctAnswerIndex: 1,
        explanation: '`JSON.parse()` deserializes a JSON string into JS data structures.',
      },
      {
        id: 'q4-4',
        question: 'What state is a Promise in when `resolve()` is invoked?',
        options: ['Pending', 'Fulfilled', 'Rejected', 'Terminated'],
        correctAnswerIndex: 1,
        explanation: 'Invoking `resolve()` transitions a Promise from pending to fulfilled state with a result value.',
      },
      {
        id: 'q4-5',
        question: 'Which array method creates a NEW array populated with results of calling a provided function on every element?',
        options: ['forEach()', 'map()', 'filter()', 'reduce()'],
        correctAnswerIndex: 1,
        explanation: '`map()` transforms each element and returns a new array of identical length.',
      },
    ],
  },
  {
    id: 'quiz-5',
    title: 'Operating Systems & Concurrency Assessment',
    subject: 'Operating Systems',
    questionsCount: 5,
    estimatedTime: '20 mins',
    difficulty: 'Beginner',
    passingPercentage: 70,
    attemptsRemaining: 2,
    maxAttempts: 3,
    lastScore: 60,
    status: 'In Progress',
    questions: [
      {
        id: 'q5-1',
        question: 'What is a Race Condition in concurrent programming?',
        options: [
          'When two threads execute faster than expected',
          'When multiple threads access shared data concurrently and the final result depends on execution timing',
          'When CPU usage reaches 100%',
          'When disk read speeds drop',
        ],
        correctAnswerIndex: 1,
        explanation: 'Race conditions happen when unsynchronized memory accesses lead to non-deterministic outcomes.',
      },
      {
        id: 'q5-2',
        question: 'Which CPU scheduling algorithm gives priority to the shortest execution time?',
        options: ['Round Robin', 'SJF (Shortest Job First)', 'FCFS (First Come First Served)', 'Priority Scheduling'],
        correctAnswerIndex: 1,
        explanation: 'SJF selects the process with the smallest burst time for execution.',
      },
      {
        id: 'q5-3',
        question: 'What is Virtual Memory?',
        options: [
          'RAM installed on cloud servers',
          'A technique that allows execution of processes that may not be completely in physical RAM',
          'Cache memory built into CPU chips',
          'Encrypted hard drive storage',
        ],
        correctAnswerIndex: 1,
        explanation: 'Virtual memory maps virtual addresses to secondary storage, expanding available memory space.',
      },
      {
        id: 'q5-4',
        question: 'What is context switching in an operating system?',
        options: [
          'Storing and restoring CPU state so execution can resume from the same point later',
          'Switching monitor resolution',
          'Replacing RAM chips',
          'Converting source code to bytecode',
        ],
        correctAnswerIndex: 0,
        explanation: 'Context switching saves state of current process/thread and loads state of next scheduled process.',
      },
      {
        id: 'q5-5',
        question: 'Which of the following is NOT a necessary condition for Deadlock?',
        options: ['Mutual Exclusion', 'Hold and Wait', 'No Preemption', 'Starvation'],
        correctAnswerIndex: 3,
        explanation: 'Starvation is a scheduling issue; Coffman deadlock conditions are Mutual Exclusion, Hold & Wait, No Preemption, and Circular Wait.',
      },
    ],
  },
  {
    id: 'quiz-6',
    title: 'Computer Networks & HTTP Protocol Quiz',
    subject: 'Computer Networks',
    questionsCount: 5,
    estimatedTime: '15 mins',
    difficulty: 'Beginner',
    passingPercentage: 70,
    attemptsRemaining: 3,
    maxAttempts: 3,
    status: 'Not Attempted',
    questions: [
      {
        id: 'q6-1',
        question: 'Which OSI model layer is responsible for end-to-end communication and port numbers?',
        options: ['Network Layer', 'Transport Layer', 'Data Link Layer', 'Application Layer'],
        correctAnswerIndex: 1,
        explanation: 'Transport Layer (Layer 4) handles TCP/UDP segmenting and port addressing.',
      },
      {
        id: 'q6-2',
        question: 'What is the HTTP status code for "Resource Not Found"?',
        options: ['200', '401', '404', '500'],
        correctAnswerIndex: 2,
        explanation: '404 Not Found indicates server could not find requested URL.',
      },
      {
        id: 'q6-3',
        question: 'What protocol translates domain names (e.g. google.com) to IP addresses?',
        options: ['DHCP', 'DNS', 'ARP', 'FTP'],
        correctAnswerIndex: 1,
        explanation: 'Domain Name System (DNS) resolves human-readable names to IP addresses.',
      },
      {
        id: 'q6-4',
        question: 'What TCP handshake step sequence establishes a connection?',
        options: ['ACK → SYN → FIN', 'SYN → SYN-ACK → ACK', 'CONNECT → OK → DATA', 'GET → POST → PUT'],
        correctAnswerIndex: 1,
        explanation: 'TCP 3-way handshake uses SYN, SYN-ACK, and ACK.',
      },
      {
        id: 'q6-5',
        question: 'What security layer protects HTTPS web traffic?',
        options: ['SSH', 'TLS/SSL', 'IPSec', 'FTP'],
        correctAnswerIndex: 1,
        explanation: 'Transport Layer Security (TLS) encrypts HTTP payloads over TCP.',
      },
    ],
  },
  {
    id: 'quiz-7',
    title: 'Git Version Control & Branching Strategy Quiz',
    subject: 'Tools & DevOps',
    questionsCount: 5,
    estimatedTime: '15 mins',
    difficulty: 'Beginner',
    passingPercentage: 75,
    attemptsRemaining: 3,
    maxAttempts: 3,
    status: 'Not Attempted',
    questions: [
      {
        id: 'q7-1',
        question: 'Which Git command creates a new branch and switches to it immediately?',
        options: ['git branch new-branch', 'git checkout -b new-branch', 'git merge new-branch', 'git status'],
        correctAnswerIndex: 1,
        explanation: '`git checkout -b` creates and checks out the branch in a single command.',
      },
      {
        id: 'q7-2',
        question: 'What does `git stash` do?',
        options: [
          'Deletes uncommitted changes permanently',
          'Temporarily shelves working directory changes without committing',
          'Pushes changes to remote server',
          'Creates a git release tag',
        ],
        correctAnswerIndex: 1,
        explanation: '`git stash` stores dirty working state onto a stack for later retrieval.',
      },
      {
        id: 'q7-3',
        question: 'What is the main difference between `git fetch` and `git pull`?',
        options: [
          '`git fetch` updates local refs without merging; `git pull` fetches and merges',
          '`git pull` is faster than `git fetch`',
          '`git fetch` deletes remote branches',
          'They perform identical operations',
        ],
        correctAnswerIndex: 0,
        explanation: '`git pull` combines `git fetch` with `git merge` automatically.',
      },
      {
        id: 'q7-4',
        question: 'How do you view commit history in terminal?',
        options: ['git show', 'git log', 'git diff', 'git check'],
        correctAnswerIndex: 1,
        explanation: '`git log` prints list of committed changes with SHA hashes and commit messages.',
      },
      {
        id: 'q7-5',
        question: 'What file excludes specific files or directories from Git tracking?',
        options: ['.env', '.gitignore', 'package.json', 'README.md'],
        correctAnswerIndex: 1,
        explanation: '.gitignore tells Git which patterns to skip.',
      },
    ],
  },
  {
    id: 'quiz-8',
    title: 'System Design Prerequisite Assessment',
    subject: 'System Design',
    questionsCount: 5,
    estimatedTime: '20 mins',
    difficulty: 'Intermediate',
    passingPercentage: 70,
    attemptsRemaining: 3,
    maxAttempts: 3,
    status: 'Not Attempted',
    questions: [
      {
        id: 'q8-1',
        question: 'What is Horizontal Scaling (Scaling Out)?',
        options: [
          'Adding more RAM/CPU to an existing machine',
          'Adding more servers/nodes to a pool of resources',
          'Decreasing database index sizes',
          'Migrating from Linux to Windows',
        ],
        correctAnswerIndex: 1,
        explanation: 'Horizontal scaling adds more machines to distribute traffic load.',
      },
      {
        id: 'q8-2',
        question: 'What role does a Load Balancer play in web architecture?',
        options: [
          'Distributes incoming network traffic across multiple backend servers',
          'Stores session data in memory',
          'Compiles TypeScript to JavaScript',
          'Encrypts SSL certificates',
        ],
        correctAnswerIndex: 0,
        explanation: 'Load balancers distribute user requests evenly to prevent single server bottlenecks.',
      },
      {
        id: 'q8-3',
        question: 'What is the primary benefit of Redis in modern web apps?',
        options: [
          'Persistent long-term data archiving',
          'Ultra-fast in-memory key-value caching',
          'Video streaming encoding',
          'Automated CSS grid generation',
        ],
        correctAnswerIndex: 1,
        explanation: 'Redis operates in RAM to cache frequent DB queries with sub-millisecond latency.',
      },
      {
        id: 'q8-4',
        question: 'In CAP Theorem, what does "C" stand for?',
        options: ['Concurrency', 'Consistency', 'Complexity', 'Computation'],
        correctAnswerIndex: 1,
        explanation: 'Consistency guarantees every read receives the most recent write or an error.',
      },
      {
        id: 'q8-5',
        question: 'What is a CDN (Content Delivery Network) used for?',
        options: [
          'Generating backend SQL queries',
          'Serving static assets (images, JS, CSS) from edge servers close to end users',
          'Managing user passwords',
          'Running database migrations',
        ],
        correctAnswerIndex: 1,
        explanation: 'CDNs cache static assets geographically closer to users to reduce latency.',
      },
    ],
  },
];

export const INITIAL_GUIDANCE_SESSIONS: GuidanceSession[] = [
  {
    id: 'guide-1',
    mentorName: 'Dr. Rajesh Verma',
    mentorTitle: 'Senior System Architect & Former Tech Lead at Microsoft',
    mentorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    title: 'Bridge Session: Transitioning from Fundamentals to Advanced DSA',
    subject: 'Data Structures',
    date: 'Aug 12, 2026',
    time: '4:00 PM - 5:30 PM IST',
    duration: '90 mins',
    mode: 'Online',
    locationOrLink: 'https://meet.google.com/xyz-bridge-dsa',
    description: 'Interactive live workshop breaking down common algorithmic pitfalls, memory management, and how to prepare for advanced tree & graph modules.',
    isRegistered: true,
    registeredCount: 42,
  },
  {
    id: 'guide-2',
    mentorName: 'Priya Sundaram',
    mentorTitle: 'Principal Staff Engineer at Amazon AWS',
    mentorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    title: 'SQL Masterclass: Query Optimization & Real-World Schema Design',
    subject: 'Database Systems',
    date: 'Aug 14, 2026',
    time: '6:00 PM - 7:30 PM IST',
    duration: '90 mins',
    mode: 'Online',
    locationOrLink: 'https://meet.google.com/sql-opt-session',
    description: 'Learn how to profile slow SQL queries, build efficient multi-column indexes, and avoid N+1 query problems in modern ORMs.',
    isRegistered: true,
    registeredCount: 58,
  },
  {
    id: 'guide-3',
    mentorName: 'Anand Kumar',
    mentorTitle: 'EpitomeTRC Academic Director & Java Lead',
    mentorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    title: 'Campus In-Person Review: Core OOPs & Clean Code Workshop',
    subject: 'Core Java',
    date: 'Aug 16, 2026',
    time: '10:00 AM - 1:00 PM IST',
    duration: '180 mins',
    mode: 'Offline',
    locationOrLink: 'EpitomeTRC Main Campus, Lab 302',
    description: 'In-person hands-on code review session where students fix design smells, apply SOLID principles, and build modular Java projects.',
    isRegistered: true,
    registeredCount: 30,
  },
  {
    id: 'guide-4',
    mentorName: 'Sneha Patel',
    mentorTitle: 'Lead Frontend Developer at Meta',
    mentorAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=200',
    title: 'Modern JS Mastery: Promises, Event Loop & React Foundation',
    subject: 'Web Development',
    date: 'Aug 18, 2026',
    time: '5:00 PM - 6:30 PM IST',
    duration: '90 mins',
    mode: 'Online',
    locationOrLink: 'https://meet.google.com/js-meta-session',
    description: 'Demystifying the JavaScript event loop, microtask queue, memory leaks, and preparing for component-driven React applications.',
    isRegistered: true,
    registeredCount: 75,
  },
  {
    id: 'guide-5',
    mentorName: 'Vikramaditya Sharma',
    mentorTitle: 'DevOps Manager at Cisco',
    mentorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
    title: 'Bridge Guidance: Git Workflows & Collaborative Engineering',
    subject: 'Tools & DevOps',
    date: 'Aug 21, 2026',
    time: '3:00 PM - 4:30 PM IST',
    duration: '90 mins',
    mode: 'Online',
    locationOrLink: 'https://meet.google.com/git-devops-cisco',
    description: 'Learn industry git practices: trunk-based development, feature flags, interactive rebasing, PR review etiquette, and CI/CD pipelines.',
    isRegistered: false,
    registeredCount: 24,
  },
  {
    id: 'guide-6',
    mentorName: 'Kavita Nambiar',
    mentorTitle: 'Senior System Architect at Flipkart',
    mentorAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=200',
    title: 'Offline Q&A: Preparing Prerequisite Mindset for Core Modules',
    subject: 'System Design',
    date: 'Aug 24, 2026',
    time: '2:00 PM - 4:00 PM IST',
    duration: '120 mins',
    mode: 'Offline',
    locationOrLink: 'EpitomeTRC Seminar Hall B',
    description: 'Interactive group session covering study strategies, overcoming foundational gaps, and Q&A with tech leaders.',
    isRegistered: false,
    registeredCount: 18,
  },
];

export const INITIAL_LEARNING_PATH_STEPS: LearningPathStep[] = [
  {
    stepNumber: 1,
    title: 'Step 1: Foundational Refreshers',
    subtitle: 'Prerequisite Core Concepts',
    description: 'Review foundational topics in Data Structures, Basic Programming Logic, OOPs, and Database queries.',
    estimatedDuration: '2.5 Hours',
    status: 'Completed',
    isUnlocked: true,
    resourceId: 'mat-1',
  },
  {
    stepNumber: 2,
    title: 'Step 2: Interactive Concept Exercises',
    subtitle: 'Hands-on Code & Practice',
    description: 'Practice programming snippets, SQL joins, array manipulation, and ES6 asynchronous functions.',
    estimatedDuration: '3 Hours',
    status: 'Completed',
    isUnlocked: true,
    resourceId: 'mat-4',
  },
  {
    stepNumber: 3,
    title: 'Step 3: Diagnostic Mini Assessments',
    subtitle: 'Self-Check Quizzes',
    description: 'Complete diagnostic assessments to evaluate strength in DSA, SQL, Java, and JavaScript fundamentals.',
    estimatedDuration: '1.5 Hours',
    status: 'In Progress',
    isUnlocked: true,
    assessmentId: 'quiz-1',
  },
  {
    stepNumber: 4,
    title: 'Step 4: Mentor Guidance & Feedback',
    subtitle: 'Live Q&A & Expert Review',
    description: 'Attend mentor guidance sessions to clarify doubts, review assessment scores, and get personalized feedback.',
    estimatedDuration: '2 Hours',
    status: 'In Progress',
    isUnlocked: true,
    resourceId: 'guide-1',
  },
  {
    stepNumber: 5,
    title: 'Step 5: Advanced Course Readiness Unlocked',
    subtitle: 'Gateway to Core Curriculum',
    description: 'Final unlock milestone demonstrating readiness for advanced System Design, Full-Stack, and AI modules.',
    estimatedDuration: '1 Hour',
    status: 'Locked',
    isUnlocked: false,
    assessmentId: 'quiz-8',
  },
];

export const INITIAL_RECOMMENDATIONS: Recommendation[] = [
  {
    id: 'rec-1',
    title: 'System Design Fundamentals: Monolith vs Microservices',
    reason: 'Prerequisite for upcoming Enterprise Architecture course',
    estimatedTime: '50 mins',
    difficulty: 'Beginner',
    type: 'Video',
    targetId: 'mat-9',
  },
  {
    id: 'rec-2',
    title: 'Operating Systems & Concurrency Assessment',
    reason: 'Score boost required for OS foundation certificate',
    estimatedTime: '20 mins',
    difficulty: 'Beginner',
    type: 'Quiz',
    targetId: 'quiz-5',
  },
  {
    id: 'rec-3',
    title: 'Git & GitHub Version Control Cheatsheet',
    reason: 'In-progress resource needing completion',
    estimatedTime: '15 mins',
    difficulty: 'Beginner',
    type: 'Notes',
    targetId: 'mat-8',
  },
  {
    id: 'rec-4',
    title: 'Computer Networks & HTTP Protocol Quiz',
    reason: 'Recommended diagnostic quiz before Web API module',
    estimatedTime: '15 mins',
    difficulty: 'Beginner',
    type: 'Quiz',
    targetId: 'quiz-6',
  },
  {
    id: 'rec-5',
    title: 'RESTful API Design Best Practices & JSON Schema',
    reason: 'Essential reading for backend RESTful development',
    estimatedTime: '25 mins',
    difficulty: 'Beginner',
    type: 'PDF',
    targetId: 'mat-10',
  },
  {
    id: 'rec-6',
    title: 'SQL Masterclass: Query Optimization & Real-World Schema',
    reason: 'Live mentor session scheduled soon with Priya Sundaram',
    estimatedTime: '90 mins',
    difficulty: 'Intermediate',
    type: 'Video',
    targetId: 'guide-2',
  },
  {
    id: 'rec-7',
    title: 'System Design Prerequisite Assessment',
    reason: 'Test your understanding of scaling & load balancing',
    estimatedTime: '20 mins',
    difficulty: 'Intermediate',
    type: 'Quiz',
    targetId: 'quiz-8',
  },
  {
    id: 'rec-8',
    title: 'Bridge Session: Transitioning from Fundamentals to Advanced DSA',
    reason: 'Recommended guidance session for algorithm readiness',
    estimatedTime: '90 mins',
    difficulty: 'Beginner',
    type: 'Video',
    targetId: 'guide-1',
  },
  {
    id: 'rec-9',
    title: 'Campus In-Person Review: Core OOPs & Clean Code Workshop',
    reason: 'Offline mentor workshop open for registration',
    estimatedTime: '180 mins',
    difficulty: 'Beginner',
    type: 'Notes',
    targetId: 'guide-3',
  },
  {
    id: 'rec-10',
    title: 'Git Version Control & Branching Strategy Quiz',
    reason: 'Validate your version control knowledge',
    estimatedTime: '15 mins',
    difficulty: 'Beginner',
    type: 'Quiz',
    targetId: 'quiz-7',
  },
];
